from __future__ import annotations

import base64
import json
import os
import sys
import urllib.request
import urllib.parse
from datetime import datetime, timedelta
from pathlib import Path
from typing import Any, Dict, List, Optional

TOKEN_SAVED_FILE = Path("ed_session_config.json")
OUTPUT_DATA_FILE = Path("ecoledirecte_donnees_completes.json")
API_BASE_URL = "https://api.ecoledirecte.com/v3"

# Default fallback student ID (Melvin BARREAU)
DEFAULT_ELEVE_ID = "8602"


def safe_base64_decode(encoded_str: Optional[str]) -> str:
    """
    Decodes Base64 HTML/text payloads returned by EcoleDirecte (common for homework details).
    """
    if not encoded_str:
        return ""
    try:
        # Resolve any incorrect base64 padding
        padded_str = encoded_str + "=" * ((4 - len(encoded_str) % 4) % 4)
        decoded_bytes = base64.b64decode(padded_str)
        return decoded_bytes.decode("utf-8", errors="ignore")
    except Exception:
        return encoded_str


def calculate_academic_year() -> str:
    """
    Dynamically calculates the current school year (e.g., '2025-2026').
    """
    now = datetime.now()
    # If we are before August (month 8), the school year started the previous year.
    if now.month < 8:
        return f"{now.year - 1}-{now.year}"
    else:
        return f"{now.year}-{now.year + 1}"


def load_session() -> Optional[Dict[str, Any]]:
    """
    Loads saved headers and tokens generated by ecoledirecte_automation.py.
    """
    if not TOKEN_SAVED_FILE.exists():
        print("[-] Fichier 'ed_session_config.json' introuvable.")
        print("    👉 Lancez d'abord la connexion 2FA avec 'python ecoledirecte_automation.py'")
        return None
    try:
        data = json.loads(TOKEN_SAVED_FILE.read_text(encoding="utf-8"))
        print(f"[✔] Session chargée depuis '{TOKEN_SAVED_FILE}'.")
        return data
    except Exception as e:
        print(f"[-] Erreur lors de la lecture du fichier de session: {e}")
        return None


def make_api_request(url: str, headers: Dict[str, str], payload: Optional[Dict[str, Any]] = None) -> Optional[Dict[str, Any]]:
    """
    Performs a robust POST request to the EcoleDirecte API.
    """
    api_headers = headers.copy()
    api_headers["Content-Type"] = "application/json"
    api_headers["Accept"] = "application/json, text/plain, */*"
    
    if payload is None:
        payload = {"data": {}}
        
    data_bytes = json.dumps(payload).encode("utf-8")
    req = urllib.request.Request(url, data=data_bytes, headers=api_headers, method="POST")
    
    try:
        with urllib.request.urlopen(req, timeout=15) as response:
            res_body = response.read().decode("utf-8")
            return json.loads(res_body)
    except Exception as e:
        endpoint = url.replace(API_BASE_URL, "")
        print(f"    [!] Erreur sur l'endpoint {endpoint}: {e}")
        return None


def get_student_id(session_data: Dict[str, Any]) -> str:
    """
    Dynamically identifies the student ID to query.
    1. Checks the command-line arguments.
    2. Checks the session file.
    3. Checks environment variables (.env / OS environment).
    4. Falls back to default '8602'.
    """
    if len(sys.argv) > 1:
        return sys.argv[1]
    
    # Check if student ID exists inside session config
    if "eleve_id" in session_data:
        return str(session_data["eleve_id"])
    if "student_id" in session_data:
        return str(session_data["student_id"])
        
    # Check environment variable
    env_id = os.getenv("ED_STUDENT_ID")
    if env_id:
        return env_id
        
    return DEFAULT_ELEVE_ID


def main() -> None:
    print("=" * 60)
    print("🚀 ECOLEDIRECTE DEEP DATA HARVESTER (PRO-EDITION)")
    print("=" * 60)
    
    session = load_session()
    if not session:
        sys.exit(1)
        
    headers = session.get("headers", {})
    eleve_id = get_student_id(session)
    school_year = calculate_academic_year()
    
    print(f"[i] Utilisation de l'élève ID: {eleve_id}")
    print(f"[i] Année scolaire calculée: {school_year}")
    print("[~] Démarrage de la récolte complète des données...")
    
    export_global: Dict[str, Any] = {
        "date_extraction": datetime.now().isoformat(),
        "eleve_id": eleve_id,
        "school_year": school_year,
        "menus": {}
    }

    # -------------------------------------------------------------------------
    # 1. PROFILE & DETAILS
    # -------------------------------------------------------------------------
    print("[->] 1/11 - Extraction du profil élève...")
    url_profile = f"{API_BASE_URL}/eleves/{eleve_id}.awp?verbe=get"
    res_profile = make_api_request(url_profile, headers, {"data": {"anneeScolaire": ""}})
    if res_profile and res_profile.get("code") == 200:
        export_global["menus"]["profile"] = res_profile.get("data")
        print("    [✔] Informations de profil récupérées.")

    # -------------------------------------------------------------------------
    # 2. NOTES & EVALUATIONS
    # -------------------------------------------------------------------------
    print("[->] 2/11 - Extraction du carnet de Notes...")
    url_notes = f"{API_BASE_URL}/eleves/{eleve_id}/notes.awp?verbe=get"
    res_notes = make_api_request(url_notes, headers, {"data": {"anneeScolaire": ""}})
    if res_notes and res_notes.get("code") == 200:
        notes_data = res_notes.get("data", {})
        export_global["menus"]["notes"] = notes_data
        notes_count = len(notes_data.get("notes", []))
        print(f"    [✔] {notes_count} notes et moyennes de périodes récupérées.")

    # -------------------------------------------------------------------------
    # 3. VIE SCOLAIRE
    # -------------------------------------------------------------------------
    print("[->] 3/11 - Extraction de la Vie Scolaire...")
    url_vie_scolaire = f"{API_BASE_URL}/eleves/{eleve_id}/viescolaire.awp?verbe=get"
    res_vs = make_api_request(url_vie_scolaire, headers)
    if res_vs and res_vs.get("code") == 200:
        export_global["menus"]["vie_scolaire"] = res_vs.get("data")
        print("    [✔] Données de vie scolaire récupérées (absences, sanctions, retards).")

    # -------------------------------------------------------------------------
    # 4. CAHIER DE TEXTES (Homework with full decoding!)
    # -------------------------------------------------------------------------
    print("[->] 4/11 - Extraction et décodage du Cahier de Textes...")
    url_agenda = f"{API_BASE_URL}/Eleves/{eleve_id}/cahierdetexte.awp?verbe=get"
    res_agenda = make_api_request(url_agenda, headers)
    if res_agenda and res_agenda.get("code") == 200:
        agenda_data = res_agenda.get("data", {})
        
        # We will iterate over the days to fetch specific homework descriptions and decode them
        detailed_homeworks = {}
        day_keys = list(agenda_data.keys())
        
        print(f"    [~] Téléchargement et décodage des devoirs détaillés pour {len(day_keys)} jours...")
        for day in day_keys:
            url_day = f"{API_BASE_URL}/Eleves/{eleve_id}/cahierdetexte/{day}.awp?verbe=get"
            res_day = make_api_request(url_day, headers)
            if res_day and res_day.get("code") == 200:
                day_details = res_day.get("data", {})
                
                # Decode base64 descriptions found inside homework parameters
                for subject in day_details.get("matieres", []):
                    # Decode 'aFaire' (homework description) if exists
                    if "aFaire" in subject and isinstance(subject["aFaire"], dict):
                        raw_content = subject["aFaire"].get("contenu")
                        subject["aFaire"]["contenu_decode"] = safe_base64_decode(raw_content)
                    # Decode 'contenuDeSeance' (lesson content) if exists
                    if "contenuDeSeance" in subject and isinstance(subject["contenuDeSeance"], dict):
                        raw_lesson = subject["contenuDeSeance"].get("contenu")
                        subject["contenuDeSeance"]["contenu_decode"] = safe_base64_decode(raw_lesson)
                
                detailed_homeworks[day] = day_details
        
        export_global["menus"]["cahier_de_textes"] = {
            "vue_ensemble": agenda_data,
            "details_jours": detailed_homeworks
        }
        print("    [✔] Liste et détails textuels des devoirs récupérés et décodés.")

    # -------------------------------------------------------------------------
    # 5. EMPLOI DU TEMPS
    # -------------------------------------------------------------------------
    print("[->] 5/11 - Extraction de l'Emploi du temps...")
    url_edt = f"{API_BASE_URL}/E/{eleve_id}/emploidutemps.awp?verbe=get"
    
    # Dynamically extract 2 weeks behind to 3 weeks ahead for a solid schedule block
    today_dt = datetime.now()
    date_debut = (today_dt - timedelta(days=14)).strftime("%Y-%m-%d")
    date_fin = (today_dt + timedelta(days=21)).strftime("%Y-%m-%d")
    
    payload_edt = {
        "data": {
            "dateDebut": date_debut,
            "dateFin": date_fin,
            "avecCoursAnnule": True
        }
    }
    res_edt = make_api_request(url_edt, headers, payload_edt)
    if res_edt and res_edt.get("code") == 200:
        export_global["menus"]["emploi_du_temps"] = res_edt.get("data")
        print(f"    [✔] Emploi du temps récupéré du {date_debut} au {date_fin}.")

    # -------------------------------------------------------------------------
    # 6. MESSAGERIE (Inbox lists & full message bodies!)
    # -------------------------------------------------------------------------
    print("[->] 6/11 - Extraction de la Messagerie...")
    url_messages = f"{API_BASE_URL}/eleves/{eleve_id}/messages.awp?verbe=getall"
    payload_msg = {
        "data": {
            "anneeMessages": school_year
        }
    }
    res_msg = make_api_request(url_messages, headers, payload_msg)
    if res_msg and res_msg.get("code") == 200:
        msg_data = res_msg.get("data", {})
        received_list = msg_data.get("messages", {}).get("received", [])
        print(f"    [✔] {len(received_list)} emails trouvés dans la boîte de réception.")
        
        # Download the contents of the top 15 most recent messages
        recent_msg_details = []
        limit = min(15, len(received_list))
        if limit > 0:
            print(f"    [~] Récupération du contenu détaillé pour les {limit} derniers messages...")
            for msg in received_list[:limit]:
                msg_id = msg.get("id")
                url_detail = f"{API_BASE_URL}/eleves/{eleve_id}/messages/{msg_id}.awp?verbe=get&mode=destinataire"
                res_detail = make_api_request(url_detail, headers, {"data": {"anneeMessages": school_year}})
                if res_detail and res_detail.get("code") == 200:
                    detail_content = res_detail.get("data", {})
                    # Automatically decode message content (often base64 or raw HTML)
                    raw_body = detail_content.get("texteMessage")
                    detail_content["texteMessage_decode"] = safe_base64_decode(raw_body)
                    recent_msg_details.append(detail_content)
        
        export_global["menus"]["messagerie"] = {
            "structure": msg_data,
            "details_recents": recent_msg_details
        }
        print("    [✔] Boîte aux lettres et détails des correspondances sauvegardés.")

    # -------------------------------------------------------------------------
    # 7. MON CLOUD / PORTE-DOCUMENTS
    # -------------------------------------------------------------------------
    print("[->] 7/11 - Extraction de 'Mon Cloud' (Porte-documents)...")
    url_cloud = f"{API_BASE_URL}/cloud/E/{eleve_id}.awp?verbe=get"
    res_cloud = make_api_request(url_cloud, headers)
    if res_cloud and res_cloud.get("code") == 200:
        export_global["menus"]["cloud"] = res_cloud.get("data")
        print("    [✔] Arborescence de fichiers et dossiers cloud récupérée.")

    # -------------------------------------------------------------------------
    # 8. ESPACES DE TRAVAIL
    # -------------------------------------------------------------------------
    print("[->] 8/11 - Extraction des Espaces de travail...")
    url_workspaces = f"{API_BASE_URL}/E/{eleve_id}/espacestravail.awp?verbe=get"
    res_ws = make_api_request(url_workspaces, headers)
    if res_ws and res_ws.get("code") == 200:
        export_global["menus"]["espaces_de_travail"] = res_ws.get("data")
        print("    [✔] Liste des espaces de travail collaboratifs récupérée.")

    # -------------------------------------------------------------------------
    # 9. DOCUMENTS ADMINISTRATIFS
    # -------------------------------------------------------------------------
    print("[->] 9/11 - Extraction des Documents administratifs...")
    url_docs = f"{API_BASE_URL}/elevesDocuments.awp?archive=&verbe=get"
    res_docs = make_api_request(url_docs, headers)
    if res_docs and res_docs.get("code") == 200:
        export_global["menus"]["documents_administratifs"] = res_docs.get("data")
        print("    [✔] Documents administratifs (bulletins, factures, etc.) listés.")

    # -------------------------------------------------------------------------
    # 10. MANUELS NUMERIQUES
    # -------------------------------------------------------------------------
    print("[->] 10/11 - Extraction des Manuels & ressources...")
    url_manuels = f"{API_BASE_URL}/Eleves/{eleve_id}/manuelsNumeriques.awp?verbe=get"
    res_manuels = make_api_request(url_manuels, headers)
    if res_manuels and res_manuels.get("code") == 200:
        export_global["menus"]["manuels_numeriques"] = res_manuels.get("data")
        print("    [✔] Manuels scolaires et ressources numériques identifiés.")

    # -------------------------------------------------------------------------
    # 11. FORMULAIRES & SONDAGES
    # -------------------------------------------------------------------------
    print("[->] 11/11 - Extraction des Formulaires & Sondages...")
    url_polls = f"{API_BASE_URL}/rdt/sondages.awp?verbe=get"
    res_polls = make_api_request(url_polls, headers)
    polls_data = res_polls.get("data") if (res_polls and res_polls.get("code") == 200) else {}

    url_forms = f"{API_BASE_URL}/edforms.awp?verbe=get"
    payload_forms = {
        "data": {
            "anneeForms": school_year,
            "typeEntity": "E",
            "idEntity": int(eleve_id)
        }
    }
    res_forms = make_api_request(url_forms, headers, payload_forms)
    forms_data = res_forms.get("data") if (res_forms and res_forms.get("code") == 200) else {}

    export_global["menus"]["formulaires_et_sondages"] = {
        "sondages": polls_data,
        "formulaires": forms_data
    }
    print("    [✔] Formulaires et sondages récupérés.")

    # -------------------------------------------------------------------------
    # SAVE HARVEST DATA TO FILE
    # -------------------------------------------------------------------------
    print("\n[+] Finalisation de l'extraction de données...")
    try:
        OUTPUT_DATA_FILE.write_text(
            json.dumps(export_global, indent=4, ensure_ascii=False),
            encoding="utf-8"
        )
        print("=" * 60)
        print(f"🎉 RUSSITE ! Les données complètes ont été exportées.")
        print(f"📂 Fichier créé: '{OUTPUT_DATA_FILE.resolve()}'")
        print("=" * 60)
    except Exception as e:
        print(f"[-] Échec de la sauvegarde du fichier JSON final: {e}")


if __name__ == "__main__":
    main()